# 34 NumPy Exercises with Hints

This is a collection of exercises that have been selected from <https://github.com/rougier/numpy-100>


#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()

1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [5]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [6]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: Use slicing)

In [7]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [8]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [35]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [10]:
Z = np.random.random((3,3,3))
print(Z)

[[[5.55016558e-01 3.18344714e-01 6.58299510e-01]
  [1.31169706e-01 2.29870603e-01 9.45865776e-01]
  [3.25881817e-04 6.14283484e-01 8.03117234e-02]]

 [[7.58440836e-01 3.98674931e-01 1.61578687e-01]
  [4.28288839e-02 8.25945838e-01 7.51327919e-01]
  [7.65793584e-01 3.20351199e-01 1.10578338e-01]]

 [[5.56919842e-01 3.61989780e-01 5.82260178e-01]
  [5.26036923e-01 5.30288937e-01 5.46790182e-01]
  [8.04082167e-01 5.06004221e-01 4.00446715e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [4]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.007366699933910259 0.9951213028124748


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [12]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.6042270215356769


#### 15. Create a 10x10 array with 1 on the border and 0 inside (★☆☆) 
(**hint**: Use slicing)

In [13]:
Z = np.ones((10,10), dtype=int)
Z[1:-1,1:-1] = 0
print(Z)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [27]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. With the help of Boolean masking, extract from the array `np.array([3,4,6,10,24,89,45,43,46,99,100])` the numbers (★☆☆) 

* which are not divisible by 3
* which are divisible by 5
* which are divisible by 3 and 5
* which are divisible by 3 and set them to 42

(**hint**: Use the modulo operator and logical_and)


In [16]:
import numpy as np
a = np.array([3,4,6,10,24,89,45,43,46,99,100])
print(a[a%3!=0])
print(a[a%5==0])
print(a[np.logical_and(a%3==0, a%5==0)])
a[a%3==0]=42
a

[  4  10  89  43  46 100]
[ 10  45 100]
[45]


array([ 42,   4,  42,  10,  42,  89,  42,  43,  46,  42, 100])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [28]:
Z = np.random.random((5,5))
print(Z.dtype)
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)
print(Z.mean())
print(Z.std())

float64
[[ 1.27501725  1.02623773  1.06283188 -1.40283514  0.8605965 ]
 [-0.77291797 -0.77827872 -0.69203791  0.13997649 -0.78703227]
 [ 1.60757073 -0.2813994  -0.85924019  1.88083955 -1.04676742]
 [-0.77270031  0.78101889  2.02970912 -0.47721072 -0.74842273]
 [-0.59761024 -0.94423519 -0.40171864  0.49566166 -0.59705294]]
3.1086244689504386e-17
1.0


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [29]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
np.dot?
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array with elements from 0-10, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=, optional `out` argument)

In [19]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 30. Create two 1D arrays with 10 random integers between 0 and 10 and find the values which they have in common? (★☆☆) 
(**hint**: np.intersect1d)

In [40]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))


[0 1 2 9]


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [61]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [75]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 39. Create an array with values ranging from 0 to 1 and elements inbetween which are spaced 0.1 (★★☆) 
(**hint**: np.linspace)

In [77]:
Z = np.linspace(0,1,11)
print(Z)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### 40. Create a random array of size 10 and sort it (★★☆) 
(**hint**: sort)

In [24]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.0636488  0.10694433 0.23243218 0.31899871 0.39292309 0.49827517
 0.56883722 0.61708371 0.881218   0.90899847]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [25]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [90]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.64687293 0.50968539 0.62501569 0.15222516 0.70450765 0.12668412
 0.42504899 0.         0.26485316 0.74627679]


#### 50. How to find the closest value (to a given scalar) in a vector to another given value? (★★☆)

(**hint**: argmin)

In [8]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
43.94700393740541
44


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [94]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(X.mean(axis=1).shape)
print(X.mean(axis=1, keepdims=True).shape)
print(Y)



[[0.4853655  0.35700907 0.8840838  0.80950537 0.82107063 0.03816039
  0.64660779 0.85561037 0.7225535  0.84855415]
 [0.304978   0.63503189 0.50264206 0.31422065 0.48438987 0.23498768
  0.41207422 0.53347669 0.46011383 0.47028996]
 [0.48457277 0.80399005 0.46798247 0.18433704 0.73638651 0.32882384
  0.96605474 0.7414736  0.94807232 0.13180358]
 [0.49288105 0.69888433 0.30297417 0.23954549 0.53991518 0.79272621
  0.48539199 0.27165892 0.12239064 0.11446779]
 [0.73202757 0.91515716 0.41704828 0.74326038 0.79310729 0.89431904
  0.39621918 0.82039161 0.08383352 0.28992049]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [102]:
Z = np.random.randint(0,10,(3,3))
print(Z)

print(Z[:,1].argsort())
print(Z[Z[:,1].argsort()])

[[3 1 5]
 [3 5 5]
 [9 8 4]]


#### 60. How to tell if a given 2D array has an all zero column(s)? (★★☆) 
(**hint**: any, ~)

In [107]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print(Z.any(axis=0))
np.any?
print((~Z.any(axis=0)).any())

[[2 0 1 0 1 0 1 1 2 2]
 [2 0 0 0 1 2 0 2 0 1]
 [2 1 2 0 2 2 0 1 2 0]]
[ True  True  True False  True  True  True  True  True  True]
True


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [31]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.36982463, 1.40980447, 1.25090671, 0.33987177, 1.20237796])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [32]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [33]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [34]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([ 0.825467  ,  0.98844356, -0.00236634, -0.59020821,  0.47273992,
        0.28409176, -0.23661799,  0.17234195,  0.26762296,  0.62064282,
        0.77081868,  0.40270112,  0.68334834,  0.18545342, -0.54633905,
       -0.90716046,  0.62428168, -0.72409721,  0.13972433, -0.71125766,
        0.72692176,  0.17866422, -0.0075997 , -0.5780792 ,  0.03617162,
       -0.59289499,  0.30340633, -0.85890117,  0.05689463, -0.96976565,
       -0.18971577,  0.03709833,  0.97855607,  0.42549888,  0.92676519,
        0.61306481,  0.40143333, -0.92581685,  0.99607343, -0.7258885 ,
        0.59820034,  0.14516685, -0.56845215, -0.49148466,  0.79507107,
       -0.86582494, -0.54897727,  0.09730986, -0.15423303, -0.08233   ,
        0.88647096, -0.92312256, -0.98143497,  0.57718461,  0.95679728,
       -0.45374979,  0.31808627,  0.33803994, -0.11538407, -0.31583582,
       -0.6323327 ,  0.65958389, -0.99965211, -0.29270341, -0.52206754,
       -0.03500223, -0.44139776,  0.07493862,  0.64265611, -0.23